In [1]:
import scipy
from scipy import stats
import numpy as np

In [2]:
# criação de dados
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,0,5,10]])
novoUser = [8,0,2,3,0]
nao_assistidos = [0,1,0,0,1]
print(matrix)
nomeFilmes = ['Round 6', 'A Invocação do Mal', '9 Desconhecidos', 'You', 'La Casa de Papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [4]:
#  cria uma lista chamada similarity com 3 elementos, todos inicializados com o valor 0
similarity = [0] * 3
print(matrix[0][0])
print(matrix[1][0])
print(matrix[1,:])
# para cada usuário no sistema
for i in range(0, 3):
  # vamos pegar os dados desse usuários
  temp = matrix[i, :]

  print(i, temp)
  tempUser = [t for n, t in zip(novoUser, temp) if n != 0]
  tempNovoUser = [n for n in novoUser if n != 0]

  # para verificar o processo
  print('user', i)
  print(tempUser, tempNovoUser)

  # biblioteca scipy.stats calcua o pearson
  # Calcula o coeficiente de correlação de Pearson entre as duas listas
  similarity[i] = scipy.stats.pearsonr(tempUser, tempNovoUser)[0]
print()

print(similarity)


8
5
[5 6 1 8 9]
0 [8 0 3 4 6]
user 0
[8, 3, 4] [8, 2, 3]
1 [5 6 1 8 9]
user 1
[5, 1, 8] [8, 2, 3]
2 [ 8  0  0  5 10]
user 2
[8, 0, 5] [8, 2, 3]

[0.9994237971287663, 0.23621543814299698, 0.8723686098443353]


In [8]:
nota_peso = np.zeros((3,5))

for nUser in range(3):
  for nFilme in range(5):
    print('nota_peso[',nUser,'][',nFilme,'] = nao_assistidos[',nFilme,'] * matrix[',nUser,'][',nFilme,'] * similarity[',nUser,']')
    print('nota_peso[',nUser,'][',nFilme,'] = ', nao_assistidos[nFilme], ' * ',matrix[nUser][nFilme],' * ', similarity[nUser])
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

print(nota_peso)

nota_peso[ 0 ][ 0 ] = nao_assistidos[ 0 ] * matrix[ 0 ][ 0 ] * similarity[ 0 ]
nota_peso[ 0 ][ 0 ] =  0  *  8  *  0.9994237971287663
nota_peso[ 0 ][ 1 ] = nao_assistidos[ 1 ] * matrix[ 0 ][ 1 ] * similarity[ 0 ]
nota_peso[ 0 ][ 1 ] =  1  *  0  *  0.9994237971287663
nota_peso[ 0 ][ 2 ] = nao_assistidos[ 2 ] * matrix[ 0 ][ 2 ] * similarity[ 0 ]
nota_peso[ 0 ][ 2 ] =  0  *  3  *  0.9994237971287663
nota_peso[ 0 ][ 3 ] = nao_assistidos[ 3 ] * matrix[ 0 ][ 3 ] * similarity[ 0 ]
nota_peso[ 0 ][ 3 ] =  0  *  4  *  0.9994237971287663
nota_peso[ 0 ][ 4 ] = nao_assistidos[ 4 ] * matrix[ 0 ][ 4 ] * similarity[ 0 ]
nota_peso[ 0 ][ 4 ] =  1  *  6  *  0.9994237971287663
nota_peso[ 1 ][ 0 ] = nao_assistidos[ 0 ] * matrix[ 1 ][ 0 ] * similarity[ 1 ]
nota_peso[ 1 ][ 0 ] =  0  *  5  *  0.23621543814299698
nota_peso[ 1 ][ 1 ] = nao_assistidos[ 1 ] * matrix[ 1 ][ 1 ] * similarity[ 1 ]
nota_peso[ 1 ][ 1 ] =  1  *  6  *  0.23621543814299698
nota_peso[ 1 ][ 2 ] = nao_assistidos[ 2 ] * matrix[ 1 ][ 2 ] * simi